#+TITLE: Easy Notmuch - lieer sync emacs

This repository provides the notmuch-sync function for effortless syncing between notmuch and [[https://github.com/gauteh/lieer][lieer]] (GMail)

It nerved me a lot that every time I wanted to fetch new email using lieer I had to leave emacs (I do not use shell within emacs) and then run "gmi sync" then start up a notmuch-search buffer.  So, I wrote this.

* Elisp function (async)

Fix paths if needed and place the code in your Emacs config (init file or separate notmuch-sync.el)

This more optimised version runs notmuch new asynchronously. Emacs does not freeze often like before or when the email database is huge.

Ahh... finally done correctly

#+BEGIN_SRC emacs-lisp
(notmuch-sync)
#+END_SRC

1. notmuch new is executed directly

2. The pre-new hook handles lieer / gmi sync.
   example:
   #+begin_src shell
     #!/usr/bin/zsh

     # Two threaded fetching
     (cd ~/.mail/gamo-tin-trela-mou.gmail/   && gmi sync) &
     (cd ~/.mail/gamo-tin-trela-mou-2.gmail/ && gmi sync) &

     wait
   #+end_src

3. Output is written to *notmuch-sync*

Manual sync:

M-x notmuch-sync

* Behaviour

- If a sync is already running --> it aborts with an error

- On success --> the current notmuch buffer is refreshed and cursor position is preserved

- On failure --> *notmuch-sync* is shown with full stderr output

* Notes

- Fully asynchronous --> Emacs does not freeze

- Debug output shown

- Requires executable pre-new hook

Recommended to enable lexical binding:

#+BEGIN_SRC
;;; -- lexical-binding: t; --
#+END_SRC
